modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="tames_dreams"
version="0.1"
displayName="The Dream lands"
displayURL="https://mcreator.net"
credits="Made with love and Care as well help from MCreator - https://mcreator.net/about"
authors="Tameable, MCreator"
description="Explore a new type of land... your dreams and master the power of your dreams."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tames_dreams]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tames_dreams]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




[[mixins]]
    config="mixins.tames_dreams.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration