modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="tames_hodpod"
version="0.1"
displayName="Tame's HodgePodge"
displayURL="https://mcreator.net"
credits="Made with love and Care as well help from MCreator - https://mcreator.net/about"
authors="Tameable, MCreator"
description="A Mod Made by Tameable, in this mod there is a hodgepodge of changes and additions to your Minecraft Gameplay! There is no General Theme, but Sometimes things from this mod may be added to my future mods!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.tames_hodpod]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tames_hodpod]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.tames_hodpod]]
modId="jei"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


[[mixins]]
    config="mixins.tames_hodpod.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration